"""Moments: montages made from photos the library already knows belong together."""
import os

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse
from pydantic import BaseModel

from .. import config, db
from ..jobs import moments as moments_job
from ..jobs.runner import manager
from ..services import moments as svc

router = APIRouter()


class MomentIn(BaseModel):
    kind: str          # event | person | place | day
    ref: str
    track: str | None = None


def _row(m) -> dict:
    d = dict(m)
    d["playable"] = bool(m["rel_path"]) and (config.MOMENTS_DIR / m["rel_path"]).exists()
    return d


@router.get("/moments")
def list_moments():
    return [_row(m) for m in db.query("SELECT * FROM moments ORDER BY created_at DESC")]


@router.get("/moments/music")
def music():
    """What a moment can be scored with. Generated by this project rather than
    licensed from anyone, so there is nothing to attribute and nothing to
    switch off."""
    return {"tracks": svc.music_tracks()}


@router.get("/moments/suggestions")
def suggestions(limit: int = 12):
    """Sources worth making one of, best first.

    Events with enough in them, biggest first — the trips someone actually
    took. Offered rather than made: rendering every event on a large library
    would be an hour of CPU nobody asked for."""
    rows = db.query(
        "SELECT e.id, e.title, COUNT(*) n, MAX(ei.file_id) cover FROM events e "
        "JOIN event_items ei ON ei.event_id = e.id "
        "JOIN files f ON f.id = ei.file_id AND f.status='active' AND f.media_type='photo' "
        "WHERE f.id NOT IN (SELECT file_id FROM locked_items) "
        "GROUP BY e.id HAVING n >= ? ORDER BY n DESC LIMIT ?",
        (svc.MIN_ITEMS, limit))
    made = {m["ref"] for m in db.query("SELECT ref FROM moments WHERE kind='event'")}
    return [{"kind": "event", "ref": str(r["id"]), "title": r["title"],
             "count": r["n"], "cover_file_id": r["cover"], "already": str(r["id"]) in made}
            for r in rows]


@router.post("/moments")
def create(body: MomentIn):
    if body.kind not in ("event", "person", "place", "day"):
        raise HTTPException(400, "a moment is of an event, a person, a place or a day")
    try:
        svc.source_for(body.kind, body.ref)
    except svc.MomentError as e:
        raise HTTPException(404, str(e)) from e
    picks = svc.curate(svc.candidates(body.kind, body.ref))
    if len(picks) < svc.MIN_ITEMS:
        raise HTTPException(
            400, f"only {len(picks)} usable photos there — a moment needs at least {svc.MIN_ITEMS}")
    moment_id = moments_job.create(body.kind, body.ref, body.track)
    job_id = manager.create("moment")
    manager.start(job_id, moments_job.run_render(job_id, moment_id))
    return {"moment_id": moment_id, "job_id": job_id, "photos": len(picks)}


@router.post("/moments/{moment_id}/remake")
def remake(moment_id: int, body: MomentIn | None = None):
    m = db.query_one("SELECT * FROM moments WHERE id=?", (moment_id,))
    if not m:
        raise HTTPException(404, "no such moment")
    if body and body.track:
        db.execute("UPDATE moments SET track=? WHERE id=?", (body.track, moment_id))
    job_id = manager.create("moment")
    manager.start(job_id, moments_job.run_render(job_id, moment_id))
    return {"moment_id": moment_id, "job_id": job_id}


@router.get("/moments/{moment_id}/video")
def video(moment_id: int, request: Request):
    m = db.query_one("SELECT * FROM moments WHERE id=?", (moment_id,))
    if not m or not m["rel_path"]:
        raise HTTPException(404, "that moment hasn’t been made yet")
    path = config.MOMENTS_DIR / m["rel_path"]
    if not path.exists():
        raise HTTPException(404, "the file is gone — make it again")
    # FileResponse speaks the whole of RFC 7233, which is what a <video> element
    # needs to seek. Hand-rolling ranges here is the bug the viewer already had.
    return FileResponse(path, media_type="video/mp4", filename=f"{m['title']}.mp4")


@router.delete("/moments/{moment_id}")
def delete(moment_id: int):
    m = db.query_one("SELECT * FROM moments WHERE id=?", (moment_id,))
    if not m:
        raise HTTPException(404, "no such moment")
    if m["rel_path"]:
        try:
            os.unlink(config.MOMENTS_DIR / m["rel_path"])
        except OSError:
            pass
    db.execute("DELETE FROM moments WHERE id=?", (moment_id,))
    return {"ok": True}
